- name: Install To Do app on new web server
  hosts: webservers
  vars_prompt:
  - name: trello_key
    prompt: Trello key?
    private: true
  - name: trello_token
    prompt: Trello token?
    private: true
  - name: board_id
    prompt: Board ID?
    default: tQnIJCnA
  remote_user: ec2-user
  tasks:
  - name: Install git and python3
    ansible.builtin.yum:
      state: present
      name:
        - git
        - python3
  - name: Install poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
  - name: Create app directory
    become: yes
    ansible.builtin.file:
      path: /opt/todoapp
      owner: ec2-user
      state: directory
      mode: '755'
  - name: Pull repo
    ansible.builtin.git:
      repo: https://github.com/KieranMackey/DevOps-Course-Starter.git
      dest: /opt/todoapp
      version: exercise-4
  - name: Install dependencies
    ansible.builtin.shell: cd /opt/todoapp && /home/ec2-user/.local/bin/poetry install
  - name: Create .env file
    ansible.builtin.template:
      src: /home/ec2-user/.env.j2
      dest: /opt/todoapp/.env
      mode: '755'
  - name: Copy todoapp service file
    become: yes
    ansible.builtin.copy:
      src: /home/ec2-user/todoapp.service
      dest: /etc/systemd/system/todoapp.service
  - name: Run todoapp service
    become: yes
    ansible.builtin.systemd:
      name: todoapp
      daemon_reload: true
      state: restarted

